import { AlertCircle, LineChart, Shield, Check, ListChecks } from 'lucide-react';

export default function IndoorAirQuality() {
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-16 text-left animate-fade-in" id="iaq-view">
      
      {/* 1. HERO DESCRIPTION */}
      <div className="max-w-3xl space-y-4">
        <span className="inline-flex items-center gap-1.5 px-3 py-1 bg-amber-50 text-amber-700 border border-amber-200 rounded-full text-xs font-bold uppercase tracking-wider">
          📊 ENVIRONMENTAL PROTECTION AGENCY STATISTICS INDEX
        </span>
        <h1 className="text-4xl sm:text-5xl font-extrabold text-slate-900 tracking-tight leading-none uppercase">
          Indoor Air Quality. <br />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-amber-600 to-amber-800">
            The Science of Breathing
          </span>
        </h1>
        <p className="text-slate-600 text-sm leading-relaxed">
          The Average American spends approximately <strong>90% of their lives indoors</strong>, where concentrations of airborne pollutants are frequently <strong>2 to 5 times higher</strong> than typical outdoor concentrations (and sometimes exceed 100 times outdoor limits in locked winter properties). Our localized stats align directly with national health databases.
        </p>
      </div>

      {/* 2. DYNAMIC METRIC CARDS */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 font-semibold">
        <div className="p-6 bg-white border border-slate-205 rounded-2xl relative overflow-hidden flex flex-col justify-between h-48 shadow-sm border border-slate-200">
          <span className="text-3xl font-black text-amber-655 text-amber-600">2-5x</span>
          <div>
            <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider">Pollution Multiplier</h4>
            <p className="text-[11px] text-slate-500 mt-1 leading-relaxed">Indoor air pollution multiplier compared to typical rural outdoor settings (EPA Source index).</p>
          </div>
        </div>

        <div className="p-6 bg-white border border-slate-205 rounded-2xl relative overflow-hidden flex flex-col justify-between h-48 shadow-sm border border-slate-200">
          <span className="text-3xl font-black text-slate-900">40 lbs</span>
          <div>
            <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider">Annual Household Dust</h4>
            <p className="text-[11px] text-slate-500 mt-1 leading-relaxed">Approximate dust, allergen, and skin fragment build-up generated by a standard 6-room family home annually.</p>
          </div>
        </div>

        <div className="p-6 bg-white border border-slate-205 rounded-2xl relative overflow-hidden flex flex-col justify-between h-48 shadow-sm border border-slate-200">
          <span className="text-3xl font-black text-slate-900">35 Million</span>
          <div>
            <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider">Asthma Patients</h4>
            <p className="text-[11px] text-slate-500 mt-1 leading-relaxed">Americans diagnosed with active respiratory dander sensitivities or seasonal bronchial asthma.</p>
          </div>
        </div>

        <div className="p-6 bg-white border border-slate-205 rounded-2xl relative overflow-hidden flex flex-col justify-between h-48 shadow-sm border border-slate-200">
          <span className="text-3xl font-black text-amber-655 text-amber-600">15%</span>
          <div>
            <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider">HVAC Utility Slashes</h4>
            <p className="text-[11px] text-slate-500 mt-1 leading-relaxed font-semibold">Average drop in heating and fuel bills after extraction of thick particulate blockages from evaporator plates.</p>
          </div>
        </div>
      </div>

      {/* 3. PARTICULATE WEIGHT & SIZES BREAKDOWN */}
      <div className="bg-white border-2 border-amber-100 rounded-3xl p-6 lg:p-8 space-y-6 shadow-sm">
        <div className="space-y-1">
          <span className="text-xs text-amber-650 text-amber-600 font-bold uppercase tracking-widest">PARTICULATE SIZE BREAKDOWN</span>
          <h2 className="text-2xl font-bold tracking-tight text-slate-900 mt-1 uppercase">
            Understanding PM2.5 and Smaller Contaminants
          </h2>
          <p className="text-slate-500 text-xs">Different particulate diameters carry distinct health implications for respiratory systems.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 font-semibold">
          <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 space-y-2 shadow-sm">
            <span className="text-xs font-black text-rose-600 uppercase tracking-widest block font-bold">PM 10 (Large Dust/Pollen)</span>
            <p className="text-slate-650 text-xs leading-relaxed">
              Includes coarse sand, visible sawdust, and heavy flower danders. These particles settle quickly into main return trunks, causing noticeable build-up over several years.
            </p>
          </div>

          <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 space-y-2 shadow-sm font-semibold">
            <span className="text-xs font-black text-amber-600 uppercase tracking-widest block font-bold">PM 2.5 (Fine Soot/Dander)</span>
            <p className="text-slate-655 text-xs leading-relaxed">
              Consists of fine vehicle exhaust, synthetic carpet fibers, and microscopic skin cells. These fine particles can remain suspended in indoor drafts for hours unless removed by proper air filtration.
            </p>
          </div>

          <div className="bg-slate-50 p-4 rounded-xl border border-slate-250 p-4 rounded-xl border border-slate-200 space-y-2 shadow-sm font-semibold">
            <span className="text-xs font-black text-red-650 text-red-600 uppercase tracking-widest block font-bold">PM 0.3 (Mold Spores/Bacteria)</span>
            <p className="text-slate-650 text-xs leading-relaxed">
              Includes microscopic mold spores and active viruses. These tiny bio-agents can bypass standard filters, cultivating biological layers inside dark attics and plenum boxes.
            </p>
          </div>
        </div>
      </div>

      {/* 4. HEALTH CORRELATION STUDY SUMMARY */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
        <div className="lg:col-span-7 space-y-4 font-semibold">
          <span className="text-xs text-amber-600 font-bold uppercase tracking-widest animate-pulse">
            BIO-AEROSOL HEALTH ADVISORY
          </span>
          <h2 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight uppercase leading-none">
            How Dusty Ventilation Systems Impact Indoor Health
          </h2>
          <p className="text-slate-650 text-xs leading-relaxed">
            Duct lint is not inert. It consists of dead skin cells, hair, starch granules, building fibers, and pet dander. In high-humidity climates, this organic mix absorbs moisture, forming an ideal substrate for fungal mold mycelium and dust-mite colonies.
          </p>
          <p className="text-slate-655 text-xs leading-relaxed font-semibold">
            As air circulates, physical turbulence detaches dry allergen fragments from duct walls. When inhaled, these fine biological particles can trigger nasal inflammation, itchy eyes, sinus discomfort, and asthma symptoms.
          </p>
          <div className="flex gap-4">
            <div className="flex items-center gap-1.5">
              <span className="w-4 h-4 rounded bg-emerald-50 border border-emerald-250 text-emerald-700 flex items-center justify-center font-bold text-[10px]">✓</span>
              <span className="text-[11px] text-slate-800 font-bold">ASHRAE Standard 62.2 Standardized</span>
            </div>
          </div>
        </div>

        {/* Informative advice box */}
        <div className="lg:col-span-5 bg-white border border-slate-200 p-6 rounded-2xl text-left space-y-4 shadow-sm font-semibold">
          <div className="p-3 bg-amber-50 border border-amber-100 text-amber-600 rounded-xl inline-block">
            <AlertCircle size={20} />
          </div>
          <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider">Primary Warning Checklist</h3>
          <p className="text-slate-650 text-xs leading-relaxed">
            Verify if your property requires ventilation cleaning:
          </p>
          <ul className="space-y-2 text-xs font-semibold text-slate-600">
            <li className="flex items-center gap-2">👉 Black charcoal-like lines forming on carpet borders near walls.</li>
            <li className="flex items-center gap-2">👉 Supply register grills showing visible dark rings and dust layers.</li>
            <li className="flex items-center gap-2">👉 Heavy dust settling on furniture within 48 hours of cleanings.</li>
            <li className="flex items-center gap-2">👉 Mildew or musty odors when central cooling activates.</li>
          </ul>
        </div>
      </div>

    </div>
  );
}
